# docker-compose.yml - Versión con mejor debugging

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: rag-db-local
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rag-frontend-local
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # evita que el bind mount borre node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: rag-api-local
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    depends_on:
      - db
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json
      - ./backend:/app
    command: sh -c "poetry install && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata:
