# docker-compose.yml - Versión con mejor debugging

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: rag-db-local
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: rag-api-local
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    depends_on:
      - db
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json
      - .:/app
    # 👇 AGREGAR ESTO para poder entrar al contenedor si falla
    # stdin_open: true
    # tty: true
    # 👇 OPCIONAL: Cambiar el comando para debugging
    # command: tail -f /dev/null  # Esto mantiene el contenedor vivo

volumes:
  pgdata: